//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.16 at 10:54:09 PM CEST 
//


package pl.pirog.datacollector.formatter.xml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryResultsType", propOrder = {
        "results",
        "generated",
        "url"
})
class CategoryResultsType {

    @XmlElement(required = true)
    private final AllResultsType results;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    private final XMLGregorianCalendar generated;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    private final String url;

    CategoryResultsType(AllResultsType results, XMLGregorianCalendar generated, String url) {
        this.results = results;
        this.generated = generated;
        this.url = url;
    }

    public AllResultsType getResults() {
        return results;
    }

    public XMLGregorianCalendar getGenerated() {
        return generated;
    }

    public String getUrl() {
        return url;
    }
}
