//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.16 at 10:54:09 PM CEST 
//


package pl.pirog.datacollector.formatter.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleResultsType", propOrder = {
        "name",
        "minCost",
        "image"
})
class SingleResultsType {

    @XmlElement(required = true)
    private final String name;
    @XmlElement(name = "min-cost", required = true)
    private final BigDecimal minCost;
    @XmlElement(required = true)
    private final ImageType image;

    SingleResultsType(String name, BigDecimal minCost, ImageType image) {
        this.name = name;
        this.minCost = minCost;
        this.image = image;
    }

}
